// ═══════════════════════════════════════
// PLACES DATA — 57 curated places
// Extracted from italy-planner.html
// ═══════════════════════════════════════

const DEFAULT_PLACES = [
  // ── ROME RESTAURANTS ──
  { id:"r1", name:"Roscioli Salumeria con Cucina", city:"Rome", category:"dining", lat:41.8956, lng:12.4731,
    description:"Family gourmet empire since the 1950s. Deli-restaurant hybrid with 2,800+ wine labels, 150+ cured meats, 350+ cheeses. Their cacio e pepe and carbonara are legendary. Michelin selected. Book well ahead.",
    notes:"Nathan recommendation. MUST book in advance!", source:"Nathan rec", duration_min:"90–120",cost:"€40–60/person",booking:"Book weeks ahead — very popular",best_time:"Dinner",transport:"Walk from Campo de Fiori area",accessibility:"Ground floor accessible",verdict:"essential",honest_summary:"Lives up to the hype. The cured meats and cheeses are genuinely world-class - started as a deli and the restaurant grew around it. Skip the secondi and load up on antipasti, cheeses, and pasta. The carbonara is elite. Book weeks ahead or you are not getting in. Expensive but worth it.",best_for:"Foodies who want one memorable splurge dinner in Rome. Share multiple antipasti - that is the move.",visited:false },
  { id:"r2", name:"La Taverna dei Fori Imperiali", city:"Rome", category:"dining", lat:41.8939, lng:12.4883,
    description:"Family-run since 2001 in the Monti district, steps from the Roman Forum. Low-lit rooms, exposed brick, red-checked tablecloths. Try the vignarola or cannelloni. Pacino & De Niro have dined here.",
    notes:"Nathan recommendation", source:"Nathan rec", verdict:"worth-it",honest_summary:"A genuine neighborhood trattoria that happens to be near the Forum. The exposed brick and red tablecloths feel like a movie set but it is the real deal - family-run since 2001. The vignarola and cannelloni are standouts. Not the cheapest but portions are generous and the atmosphere is warm. Celebrity sightings are a fun bonus, not the draw.",best_for:"A proper sit-down Roman dinner near the Colosseum area without resorting to tourist traps. Great after a day of ruins.",visited:false },
  { id:"r3", name:"L'Antico Forno di Fontana di Trevi", city:"Rome", category:"dining", lat:41.9012, lng:12.4840,
    description:"Quick-bite bakery right by the Trevi Fountain. Great for a cheap slice between sightseeing. Perfect grab-and-go spot.",
    notes:"Nathan recommendation — grab a slice near Trevi", source:"Nathan rec", verdict:"nice",honest_summary:"A no-frills bakery for a cheap, fast slice steps from the Trevi Fountain. Not a destination - a refueling stop. The pizza is good, not life-changing, but it costs almost nothing and saves you from the overpriced restaurants surrounding Trevi. Grab a slice, eat walking, move on.",best_for:"A quick cheap bite between sightseeing. Perfect when you are near Trevi and hungry but do not want to sit down.",visited:false },
  { id:"r4", name:"Emma Pizzeria", city:"Rome", category:"dining", lat:41.8960, lng:12.4720,
    description:"Opened near Campo de' Fiori with ties to the Roscioli family. Thin Roman-style crust with premium toppings: buffalo mozzarella from Paestum, tomatoes from Vesuvius. Wine cellar beneath ancient Theatre of Pompey.",
    notes:"Nathan recommendation", source:"Nathan rec", verdict:"worth-it",honest_summary:"The Roscioli family's pizza outpost. The crust is thin Roman-style, and the toppings are premium - buffalo mozzarella, Vesuvius tomatoes. The wine cellar beneath the Theatre of Pompey is a cool conversation piece. More polished than a neighborhood pizzeria, less intense than Roscioli proper. A solid middle ground.",best_for:"Pizza night near Campo de Fiori when you want quality but not the full Roscioli commitment. Good for a lighter meal.",visited:false },
  { id:"r5", name:"Forno Campo de' Fiori", city:"Rome", category:"dining", lat:41.8956, lng:12.4718,
    description:"Historic bakery est. 1880. The legendary pizza bianca — olive oil, salt, and perfection. Grab a slice and eat in the piazza. Also great focaccia sandwiches with premium meats.",
    notes:"Nathan recommendation — get the pizza bianca!", source:"Nathan rec", verdict:"essential",honest_summary:"The pizza bianca here is legendary for a reason - olive oil, salt, and bread so good it redefines what bread can be. Been doing it since 1880. It costs almost nothing. The focaccia sandwiches are also excellent. Eat it in the piazza and watch the market vendors. This is Rome at its simplest and best.",best_for:"Everyone. Grab a slice of pizza bianca on your way through Campo de Fiori. Takes 5 minutes, costs 2 euros, unforgettable.",visited:false },
  { id:"r6", name:"Panificio Bonci", city:"Rome", category:"dining", lat:41.9072, lng:12.4428,
    description:"Gabriele Bonci is the 'Michelangelo of pizza.' Creative pizza al taglio — mortadella with pistachio, fig with prosciutto. Saturday porchetta sandwiches are a must. Natural ingredients only.",
    notes:"Nathan recommendation — go on Saturday for porchetta", source:"Nathan rec", verdict:"essential",honest_summary:"Gabriele Bonci is not exaggerating when people call him the Michelangelo of pizza. His pizza al taglio is cut with scissors, sold by weight, and every combination is creative and perfect. The mortadella with pistachio is famous. Saturday porchetta sandwiches draw a crowd. It is near the Vatican, slightly out of the way, and totally worth the detour.",best_for:"Foodies who want the best pizza al taglio in Rome. Pair with a Vatican visit. Saturday is porchetta day.",visited:false },
  { id:"r7", name:"Pizzeria Remo a Testaccio", city:"Rome", category:"dining", lat:41.8762, lng:12.4756,
    description:"No-frills neighborhood pizzeria since 1976. Paper tablecloths, wood-fired oven, where Romans actually eat pizza. No reservations, arrive before 7pm. Pizzas under €10.",
    notes:"Nathan recommendation — dinner only, no reservations, arrive early!", source:"Nathan rec", verdict:"hidden-gem",honest_summary:"The most authentic pizza experience in Rome. Paper tablecloths, no English menu needed, wood-fired oven since 1976. Pizza is thin, crispy, under 10 euros. The vibe is loud, fast, and unapologetically Roman. Not romantic - this is where you eat like a local. Arrive before 7pm or wait.",best_for:"Couples who want a real Roman experience, not a polished tourist dinner. Budget-friendly without sacrificing quality.",visited:false },
  { id:"r8", name:"Fatamorgana Chiavari", city:"Rome", category:"dining", lat:41.8965, lng:12.4787,
    description:"Artisan gelato by Maria Agnese Spagnuolo — 300+ flavors, all natural, gluten-free. Wild combos: basil-walnut-honey, dark chocolate & tobacco. Multiple Rome locations.",
    notes:"Nathan recommendation — gelato spot", source:"Nathan rec", verdict:"worth-it",honest_summary:"Not your typical gelato shop. Maria Agnese creates genuinely weird and wonderful flavors - basil-walnut-honey, dark chocolate and tobacco. Everything is natural, no artificial colors. Multiple locations but this one near the Pantheon is convenient. If you want classic flavors done perfectly, go to Gracchi instead. If you want an adventure, this is the spot.",best_for:"Adventurous eaters who want to try gelato flavors they have never imagined. Not for purists who just want a great pistachio.",visited:false },
  { id:"r9", name:"Gelateria dei Gracchi", city:"Rome", category:"dining", lat:41.9078, lng:12.4572,
    description:"Near the Vatican in Prati. Beloved for classic flavors done perfectly — their pistachio is widely considered among the best in Rome. Small, unassuming, always packed.",
    notes:"Nathan recommendation — gelato near Vatican", source:"Nathan rec", verdict:"essential",honest_summary:"Small, unassuming, and always packed - because the gelato is flawless. Their pistachio is widely considered the best in Rome. Classic flavors executed to perfection, no gimmicks. Near the Vatican in Prati, so pair it with St. Peter's or the Vatican Museums. If you only get gelato once in Rome, make it here.",best_for:"Anyone who wants the best traditional gelato in Rome. The pistachio is the move.",visited:false },
  { id:"r10", name:"Sciascia Caffè 1919", city:"Rome", category:"dining", lat:41.9095, lng:12.4485,
    description:"Operating since 1919. Known for signature coffee served in a cup lined with dark chocolate. A beloved local institution in the Prati district — where Romans go, not tourists.",
    notes:"Nathan recommendation — coffee spot", source:"Nathan rec", verdict:"hidden-gem",honest_summary:"A century-old cafe where Romans actually go. The signature move is coffee in a cup lined with dark chocolate - the chocolate melts as you drink. It is in Prati, away from the tourist center, and the vibe is completely local. Not a place you would stumble on, which is the point.",best_for:"Coffee lovers who want an authentic Roman cafe experience away from tourist crowds. Pair with Bonci or Gracchi nearby.",visited:false },
  // ── ROME RESTAURANTS (Goop guide) ──
  { id:"g1", name:"Felice a Testaccio", city:"Rome", category:"dining", lat:41.8772, lng:12.4758,
    description:"The most famous cacio e pepe in Rome, served since 1936. The pasta is tossed tableside in a theatrical flourish. Old-school Roman trattoria in the Testaccio neighborhood — retro checkered floors, white tablecloths, packed with locals.",
    source:"Goop guide", duration_min:"90",cost:"€30–45/person",booking:"Book ahead — very popular",best_time:"Lunch or dinner",transport:"Walk from Testaccio area or tram",verdict:"essential",honest_summary:"If you eat one plate of cacio e pepe in Rome, eat it here. Felice has been perfecting this single dish since 1936 and the tableside toss is part of the experience. The rest of the menu is solid traditional Roman, but the cacio e pepe is the reason you come. Testaccio is a real Roman neighborhood — no tourist veneer. Near Pizzeria Remo, so you could do both areas the same evening.",best_for:"The definitive cacio e pepe experience. Pair with a Testaccio neighborhood evening — Remo for pizza, Felice for pasta.",visited:false },
  { id:"g2", name:"Drink Kong", city:"Rome", category:"dining", lat:41.8955, lng:12.4985,
    description:"World's 50 Best Bars list. Japanese-inspired cocktail bar in the Monti district designed like a Blade Runner set — dark hues, neon accents, counters and booths. Bartender Patrick Pistolesi is one of the world's best.",
    source:"Goop guide", duration_min:"60–90",cost:"€15–20/cocktail",booking:"Walk in or book for groups",best_time:"Evening, 9pm onwards",transport:"Walk from Monti area (near DoubleTree hotel)",verdict:"worth-it",honest_summary:"Not your typical Rome experience — this is a world-class cocktail bar that happens to be in the Monti district, walking distance from your hotel. The drinks are inventive, the space is stunning, and the vibe is completely different from everything else on your list. One or two cocktails is the right amount. Not cheap, but this is a date night spot, not a bar crawl.",best_for:"A special date night cocktail after dinner in Monti. Walk from the hotel, dress a little sharper than usual.",visited:false },
  // ── VENICE RESTAURANTS ──
  { id:"v1", name:"Al Covo", city:"Venice", category:"dining", lat:45.4347, lng:12.3484,
    description:"Michelin-recognized. Venetian chef Cesare Benelli married Texan culinary scholar Diane Rankin — opened in 1987. Fishermen deliver the catch each morning. Vegetables from their own garden on Sant'Erasmo island. Slow Food Alliance member.",
    notes:"Nathan recommendation — book well in advance!", source:"Nathan rec", duration_min:"120",cost:"€50–80/person",booking:"Book well in advance",best_time:"Dinner",transport:"Walk or vaporetto to Arsenale",accessibility:"Accessible",verdict:"essential",honest_summary:"The best restaurant on your Venice list. A genuine love story - Venetian chef married a Texan, opened this in 1987. Michelin-recognized ever since. Seafood comes straight from fishermen each morning. Diane's chocolate cake is famous. Small, intimate, personal.",best_for:"Your best dinner in Venice. This is the honeymoon splurge. Book for your first or last Venice night.",visited:false },
  { id:"v2", name:"Caffè Florian", city:"Venice", category:"dining", lat:45.4340, lng:12.3388,
    description:"Italy's oldest café, est. 1720 in Piazza San Marco. Six gilded rooms that hosted Casanova, Byron, Dickens, and Goethe. Live orchestras on the piazza. Pricey but unforgettable. Sit at the bar for lower prices.",
    notes:"Nathan recommendation — sit at bar to save money. Great conversation starter!", source:"Nathan rec", duration_min:"45–90",cost:"€12–20 per drink + €6 music surcharge",booking:"No reservation needed",best_time:"Evening for live orchestra on the piazza",transport:"Walk — right on Piazza San Marco",accessibility:"Accessible",verdict:"essential",honest_summary:"Yes, it is expensive (15+ euros for a coffee). Yes, it is touristy. But it is the oldest cafe in Italy, open since 1720, and sitting in those gilded rooms while an orchestra plays in Piazza San Marco is genuinely magical. This is a splurge for the experience, not the coffee. Sit at the bar for 1/3 the price.",best_for:"Honeymooners who want a once-in-a-lifetime cafe experience. Not for budget travelers.",visited:false },
  { id:"v3", name:"Harry's Bar", city:"Venice", category:"dining", lat:45.4320, lng:12.3370,
    description:"National Historic Monument since 2001. Est. 1931 by Giuseppe Cipriani. Birthplace of the Bellini cocktail (1948) and beef Carpaccio (1950). Hemingway's favorite Venice spot. Tiny, classic, expensive — but iconic.",
    notes:"Nathan recommendation — order a Bellini! Great story to tell.", source:"Nathan rec", duration_min:"60–90",cost:"€20+ per drink",booking:"No reservation needed",best_time:"Afternoon or early evening",transport:"Walk from San Marco (2 min)",accessibility:"Ground floor accessible",verdict:"worth-it",honest_summary:"Tiny, understated, and absurdly expensive - but this is where the Bellini was invented in 1948 and where Hemingway held court. The Bellini is the thing to order. Food is good but not life-changing for the price. You are paying for history and atmosphere. One drink is enough.",best_for:"Cocktail lovers, literary history fans. Order one Bellini, soak it in, leave happy.",visited:false },
  { id:"v4", name:"Bar Caravellino", city:"Venice", category:"dining", lat:45.4342, lng:12.3405,
    description:"A lesser-known gem for aperitivo — away from the tourist crush. The kind of local spot that makes you feel like you've discovered something real in Venice.",
    notes:"Nathan recommendation", source:"Nathan rec", verdict:"hidden-gem",honest_summary:"The kind of bar you find by accident and then tell everyone about. Away from the San Marco crush, it feels like a local secret. Good aperitivo, reasonable prices by Venice standards. No flashy history or famous cocktails - just a genuine Venetian bar where you can breathe.",best_for:"A relaxed aperitivo without tourist markup. Good palate cleanser between the big-ticket Venice experiences.",visited:false },
  { id:"v5", name:"Bar Longhi", city:"Venice", category:"dining", lat:45.4315, lng:12.3345,
    description:"Inside The Gritti Palace, a Renaissance palazzo once home to a Venetian doge. Bellinis on the Grand Canal terrace. Pure romance for a special evening.",
    notes:"Nathan recommendation — romantic date night spot!", source:"Nathan rec", verdict:"worth-it",honest_summary:"Inside The Gritti Palace - a Renaissance palazzo that was once a doge's home. Bellinis on the Grand Canal terrace are pure honeymoon fantasy. Extremely expensive, but you are paying for the setting. One drink at sunset is the right amount. Do not eat dinner here unless budget is no object.",best_for:"The ultimate romantic drink in Venice. One Bellini on the terrace at sunset. Save dinner money for Al Covo.",visited:false },
  { id:"v6", name:"Osteria Enoteca San Marco", city:"Venice", category:"dining", lat:45.4348, lng:12.3392,
    description:"Near Piazza San Marco but authentically Venetian. Great wine list and cicchetti (Venetian tapas). Relaxed spot for local wines and small bites between sightseeing.",
    notes:"Nathan recommendation", source:"Nathan rec", verdict:"nice",honest_summary:"A solid cicchetti and wine spot near San Marco that manages to feel authentically Venetian despite the location. Good for a casual lunch of small bites and local wines without a full sit-down commitment. Nothing revolutionary but reliably good and fairly priced for the area.",best_for:"A casual wine-and-cicchetti lunch between San Marco sightseeing. Low commitment, no reservation needed.",visited:false },
  // ── LAKE COMO RESTAURANTS ──
  { id:"c1", name:"Dispensa 63", city:"Lake Como", category:"dining", lat:45.9870, lng:9.2590,
    description:"Modern-rustic spot known for quality local ingredients and a warm, inviting vibe. A solid choice for a relaxed meal in the Lake Como area.",
    notes:"Nathan recommendation", source:"Nathan rec", verdict:"nice",honest_summary:"A modern-rustic restaurant with good local ingredients in the Como area. Solid but not a destination restaurant. The vibe is warm and inviting without being overly fancy. A safe choice if the other Bellagio spots are full or you want something different.",best_for:"A reliable backup dinner option. Good when you want quality without the waterfront premium.",visited:false },
  { id:"c2", name:"Ristorante Alle Darsene di Loppia", city:"Lake Como", category:"dining", lat:45.9785, lng:9.2635,
    description:"Right on the lakefront in tiny Loppia hamlet. Romantic tables overlooking the water — ideal date night spot. Fresh lake fish and classic Lombardian dishes.",
    notes:"Nathan recommendation — romantic lakeside dinner!", source:"Nathan rec", verdict:"essential",honest_summary:"Right on the lakefront in the tiny Loppia hamlet. The tables overlooking the water are genuinely romantic - this is the honeymoon dinner spot on Lake Como. Fresh lake fish, classic Lombardian cooking. Less crowded than Bellagio restaurants because it is slightly off the beaten path. Book for sunset.",best_for:"Your romantic lakeside dinner on Como. Book a waterfront table at sunset. This is the one.",visited:false },
  { id:"c3", name:"Trattoria San Giacomo", city:"Lake Como", category:"dining", lat:45.9868, lng:9.2613,
    description:"Three generations since Nonna Pina started it in 1973 in Bellagio. No reservations — arrive early. Famous for osso buco, lake fish, homemade desserts. 100+ wine labels.",
    notes:"Nathan recommendation — no reservations, arrive early! Get prosecco from wine bar across the alley while waiting.", source:"Nathan rec", verdict:"essential",honest_summary:"Three generations of family cooking since 1973. No reservations means you might wait, but the move is to grab prosecco from the wine bar across the alley (Aperitivo Et Al) while you wait. The osso buco and lake fish are famous. Over 100 wines. The kind of place where Nonna's spirit is in every dish.",best_for:"The authentic family trattoria experience in Bellagio. Arrive early or embrace the wait with prosecco across the alley.",visited:false },
  { id:"c4", name:"Ristorante Bilacus", city:"Lake Como", category:"dining", lat:45.9867, lng:9.2607,
    description:"Highly rated in Bellagio (4.3 stars, ~2,000 reviews). 'Bilacus' is the Latin name for Bellagio. Specializes in lake cuisine — risottos, fresh fish, and regional wines.",
    notes:"Nathan recommendation", source:"Nathan rec", verdict:"worth-it",honest_summary:"Highly rated with good reason - solid lake cuisine in the heart of Bellagio. Risottos and fresh fish are the strengths. The name means Bellagio in Latin, which is a nice touch. Less charming than San Giacomo but more reliable for getting a table. A strong second choice.",best_for:"A good Bellagio dinner when San Giacomo has a long wait. Solid across the board.",visited:false },
  { id:"c5", name:"Wine Bar Aperitivo Et Al", city:"Lake Como", category:"dining", lat:45.9869, lng:9.2616,
    description:"Right across from Trattoria San Giacomo in Bellagio — the perfect aperitivo spot while waiting for your table. Italian wines, Aperol Spritzes, and lovely evening ambiance.",
    notes:"Nathan recommendation — pair with San Giacomo dinner", source:"Nathan rec", verdict:"worth-it",honest_summary:"This tiny wine bar exists almost entirely as a companion to Trattoria San Giacomo across the alley. Grab prosecco or an Aperol Spritz here while waiting for your San Giacomo table. Also works as a standalone aperitivo spot with a nice evening vibe.",best_for:"Pre-dinner drinks while waiting for San Giacomo. The perfect pairing.",visited:false },
  { id:"c6", name:"Osteria Quatro Pass", city:"Lake Como", category:"dining", lat:45.9862, lng:9.2604,
    description:"Traditional Lombardian dishes in a casual osteria setting. The type of place where the menu changes with what's fresh that day.",
    notes:"Nathan recommendation", source:"Nathan rec", verdict:"nice",honest_summary:"A casual osteria where the menu changes with what is fresh. No frills, no fuss. The kind of place that is hard to have a bad meal at but unlikely to be the highlight of your trip. Good for a low-key lunch in Bellagio.",best_for:"A casual lunch when you want simple, honest Lombardian food without a production.",visited:false },
  { id:"c7", name:"Caffè Varenna", city:"Lake Como", category:"dining", lat:46.0098, lng:9.2830,
    description:"Lakeside café in colorful Varenna fishing village. Perfect for morning cappuccino or afternoon aperitivo with lake views. Quieter and more authentic than Bellagio's café scene.",
    notes:"Nathan recommendation", source:"Nathan rec", verdict:"worth-it",honest_summary:"Varenna is quieter and more authentic than Bellagio, and this lakeside cafe captures that perfectly. Morning cappuccino or afternoon aperitivo with lake views and no crowds. The vibe is relaxed in a way Bellagio cafes struggle to match.",best_for:"Morning coffee or afternoon aperitivo in Varenna. Pair with a walk along the Lovers Walk promenade.",visited:false },
  // ── ROME LANDMARKS ──
  { id:"l1", name:"Colosseum", city:"Rome", category:"landmark", lat:41.8902, lng:12.4922,
    description:"The iconic 2,000-year-old amphitheater that once held 50,000 spectators for gladiatorial games. A UNESCO World Heritage Site and Rome's most recognizable landmark.",
    notes:"Book timed entry tickets in advance! Consider combo ticket with Roman Forum.", source:"Must-see", hours_open:"9:00",hours_close:"19:00",duration_min:"120–180",cost:"€16 (combo with Forum)",booking:"Book online 2+ weeks ahead",best_time:"Early morning or late afternoon",transport:"Metro Line B → Colosseo station",accessibility:"Elevator available for upper levels",verdict:"essential",honest_summary:"The most iconic ruin in the world. Even if you have seen 1,000 photos, standing inside genuinely hits different. The exterior is arguably more impressive than the interior - but the underground tour is worth every euro. Expect crowds no matter when; early morning is least painful.",best_for:"Everyone on a first Rome visit. History buffs get extra value from the underground/arena floor tour.",visited:false },
  { id:"l2", name:"Vatican Museums & Sistine Chapel", city:"Rome", category:"landmark", lat:41.9065, lng:12.4536,
    description:"One of the world's greatest art collections, culminating in Michelangelo's Sistine Chapel ceiling. Plan for 3-4 hours minimum.",
    notes:"Book skip-the-line tickets ASAP — sells out in June.", source:"Must-see", hours_open:"8:00",hours_close:"18:30",duration_min:"180–240",cost:"€17 online",booking:"MUST book online — sells out weeks ahead",best_time:"Early morning (8am entry)",transport:"Metro Line A → Ottaviano, 10 min walk",accessibility:"Wheelchair accessible, elevator available",verdict:"essential",honest_summary:"Overwhelming in the best way. The Sistine Chapel ceiling alone justifies the visit, but the 2km of galleries before it are stacked with masterpieces. You WILL be tired by the end. Go first thing at 8am or in the last 2 hours - midday is a sardine can. Skip the audio guide, get a human guide.",best_for:"Art lovers, history buffs, anyone who wants to see the Sistine Chapel. Even non-art people are moved by it.",visited:false },
  { id:"l3", name:"St. Peter's Basilica", city:"Rome", category:"landmark", lat:41.9022, lng:12.4539,
    description:"The world's largest church, built over the tomb of Saint Peter. Michelangelo's Pietà is inside. Climb the dome for incredible city views.",
    notes:"Free entry but long lines. Go early morning. Dress code enforced (cover shoulders/knees).", source:"Must-see", hours_open:"7:00",hours_close:"18:30",duration_min:"60–90",cost:"Free (dome climb €8)",booking:"No reservation for basilica, book dome climb",best_time:"Early morning before crowds",transport:"Metro Line A → Ottaviano",accessibility:"Basilica accessible; dome has 551 steps, no elevator",verdict:"essential",honest_summary:"The sheer scale is staggering - the largest church in the world, and it feels like it. Michelangelo's Pieta alone is worth the visit. Free entry, but the lines can be brutal. The dome climb (551 steps, no elevator) rewards you with one of the best views in Rome. Dress code is enforced - cover shoulders and knees or they turn you away.",best_for:"Everyone. Go early morning for shortest lines. The dome climb is tough but the view is spectacular if you are up for it.",visited:false },
  { id:"l4", name:"Trevi Fountain", city:"Rome", category:"landmark", lat:41.9009, lng:12.4833,
    description:"Baroque masterpiece from 1762. Tradition says throwing a coin over your shoulder ensures a return to Rome. Stunning when lit at night.",
    notes:"Go early morning or late evening to avoid worst crowds.", source:"Must-see", verdict:"worth-it",honest_summary:"Genuinely beautiful, especially lit up at night. The crowd around the fountain is intense during the day - people jostling for selfie position. Best strategy: visit late at night (10-11pm) when it is magical and uncrowded, or very early morning. Takes 15-20 minutes max.",best_for:"Everyone - quick stop, not a half-day commitment. Go at night for the real experience.",visited:false },
  { id:"l5", name:"Pantheon", city:"Rome", category:"landmark", lat:41.8986, lng:12.4769,
    description:"Nearly 2,000-year-old temple with the world's largest unreinforced concrete dome. The oculus (hole in the roof) is the only light source. Free to enter.",
    notes:"Now requires timed entry reservation (€5). Book ahead.", source:"Must-see", hours_open:"9:00",hours_close:"19:00",duration_min:"30–60",cost:"€5 timed entry",booking:"Book timed entry online",best_time:"Any time — less crowded than Colosseum",transport:"Walk from Piazza Navona (5 min)",accessibility:"Ground floor accessible",verdict:"essential",honest_summary:"The single most impressive building in Rome. Nearly 2,000 years old and the dome is STILL the largest unreinforced concrete dome ever built. The oculus is mesmerizing. Only takes 20-30 minutes but you will want to stand there and stare. Way less crowded than the Colosseum.",best_for:"Everyone. Quick visit, massive impact. Architecture fans will lose their minds.",visited:false },
  { id:"l6", name:"Roman Forum", city:"Rome", category:"landmark", lat:41.8925, lng:12.4853,
    description:"The center of ancient Roman public life — temples, government buildings, and marketplaces spanning 900 years of history. Often combined with Colosseum ticket.",
    notes:"Combo ticket with Colosseum. Wear comfortable shoes.", source:"Must-see", hours_open:"9:00",hours_close:"19:00",verdict:"worth-it",honest_summary:"Where ancient Rome actually happened - 900 years of temples, courts, and markets. The combo ticket with the Colosseum makes it a natural pairing. It can feel like a confusing field of rubble without context, so a guide or good audio tour makes all the difference. Wear comfortable shoes - the ground is uneven ancient stone.",best_for:"History buffs and anyone with a Colosseum ticket (it is included). A guide transforms this from ruins into a story.",visited:false },
  { id:"l7", name:"Piazza Navona", city:"Rome", category:"landmark", lat:41.8992, lng:12.4730,
    description:"Built on the site of an ancient Roman stadium. Three ornate fountains including Bernini's Fountain of the Four Rivers. Great for evening people-watching.",
    notes:"Beautiful at night. Close to several restaurants on the list.", source:"Must-see", verdict:"worth-it",honest_summary:"One of Rome's most beautiful piazzas, built on an ancient stadium. Bernini's Fountain of the Four Rivers is the centerpiece. Best experienced in the evening when the light is golden and the street performers come out. Close to several Nathan-rec restaurants. Do not eat at the piazza restaurants - tourist trap pricing.",best_for:"An evening stroll after dinner nearby. Five minutes from Roscioli and Emma Pizzeria. Free to enjoy.",visited:false },
  { id:"l8", name:"Spanish Steps", city:"Rome", category:"landmark", lat:41.9060, lng:12.4828,
    description:"135 elegant steps connecting Piazza di Spagna to the Trinità dei Monti church above. A gathering spot since the 1700s. Surrounded by high-end shopping.",
    notes:"", source:"Must-see", verdict:"nice",honest_summary:"Pretty steps, good view from the top, surrounded by high-end shopping you probably will not buy from. Takes 10 minutes max. It is iconic but there is not much to do here beyond photos. Better as a pass-through on the way to somewhere else than a destination. The area around it is more interesting than the steps themselves.",best_for:"A quick photo stop if you are in the area. Not worth a special trip. Combine with shopping or a walk to Villa Borghese.",visited:false },
  { id:"l9", name:"Trastevere", city:"Rome", category:"activity", lat:41.8867, lng:12.4690,
    description:"Rome's most charming neighborhood for evening strolls. Cobblestone streets, ivy-covered buildings, local trattorias, and vibrant nightlife. Cross the Tiber and get lost here.",
    notes:"Great area for an evening walk after dinner.", source:"Must-see", verdict:"essential",honest_summary:"The best neighborhood in Rome for an evening wander. Cobblestone streets, ivy-covered walls, local trattorias, and a vibe that feels more like a village than a capital city. Cross the Tiber after dinner and just get lost. This is where Rome feels most romantic and least like a museum.",best_for:"Your evening stroll neighborhood. Go after dinner, no plan, just wander. Peak honeymoon energy.",visited:false },
  { id:"l10", name:"Borghese Gallery", city:"Rome", category:"landmark", lat:41.9142, lng:12.4921,
    description:"World-class art museum housing Bernini sculptures and Caravaggio paintings in a beautiful villa setting. Limited entry makes it an intimate experience.",
    notes:"Requires advance reservation — only 360 visitors per 2-hour session.", source:"Must-see", hours_open:"9:00",hours_close:"19:00",duration_min:"120",cost:"€15",booking:"MUST book — only 360 visitors per 2-hour slot",best_time:"First slot of the day",transport:"Bus or walk from city center through Villa Borghese park",accessibility:"Elevator available",verdict:"essential",honest_summary:"The most intimate museum experience in Rome. Only 360 visitors per 2-hour slot means you actually get to stand in front of a Bernini sculpture without a crowd. The Caravaggio paintings are stunning. The villa setting with gardens makes it feel like visiting a private collection. You MUST book ahead - slots sell out fast in June.",best_for:"Art lovers who want quality over quantity. The antidote to Vatican Museum crowds. Book the first slot of the day.",visited:false },
  // ── VENICE LANDMARKS ──
  { id:"l11", name:"St. Mark's Basilica", city:"Venice", category:"landmark", lat:45.4345, lng:12.3397,
    description:"Byzantine masterpiece with golden mosaics covering 8,000 sq meters of ceiling. Over 500 columns. The Pala d'Oro altarpiece is studded with thousands of gems.",
    notes:"Skip-the-line tickets available. Free entry to basilica, paid for museum/Pala d'Oro.", source:"Must-see", hours_open:"9:30",hours_close:"17:00",verdict:"essential",honest_summary:"The golden mosaics covering 8,000 square meters of ceiling are breathtaking - photos do not capture it. Over 500 columns, and the Pala d'Oro altarpiece is covered in gems. Free entry to the basilica itself, but the museum and Pala d'Oro are paid. Skip-the-line tickets are worth it in June. Smaller and more intimate than St. Peter's in Rome.",best_for:"Everyone visiting Venice. The mosaics alone justify the trip. Go in the morning for the best light through the gold.",visited:false },
  { id:"l12", name:"Doge's Palace", city:"Venice", category:"landmark", lat:45.4337, lng:12.3407,
    description:"Gothic masterpiece that was the seat of Venetian government for 700 years. The Bridge of Sighs connects it to the prison. Tintoretto's 'Paradise' is the world's largest oil painting.",
    notes:"Book ahead for Secret Itineraries tour to see hidden rooms.", source:"Must-see", hours_open:"9:00",hours_close:"18:00",verdict:"essential",honest_summary:"Seven hundred years of Venetian political power, and the building shows it. The Bridge of Sighs is more impressive from inside than from the canal. Tintoretto's Paradise painting is genuinely massive. The Secret Itineraries tour (book ahead) takes you through hidden rooms, prisons, and spy passages - way more interesting than the standard route.",best_for:"History and architecture fans. The Secret Itineraries tour is the move if you book ahead. Pair with St. Mark's Basilica next door.",visited:false },
  { id:"l13", name:"Rialto Bridge", city:"Venice", category:"landmark", lat:45.4381, lng:12.3359,
    description:"The oldest and most famous bridge across the Grand Canal, built 1588-1591. Lined with shops. The Rialto Market nearby is great for fresh produce and seafood.",
    notes:"Visit the fish market in the morning (closed Sun/Mon).", source:"Must-see", verdict:"worth-it",honest_summary:"Beautiful bridge, touristy shops, great views of the Grand Canal from the top. Takes 10 minutes to walk across. The real draw is the Rialto Market nearby - go in the morning for fresh produce and seafood (closed Sunday and Monday). The bridge itself is a photo op, not a destination.",best_for:"A quick walk-across plus morning market visit. The market is more interesting than the bridge itself.",visited:false },
  { id:"l14", name:"Murano Island", city:"Venice", category:"activity", lat:45.4585, lng:12.3520,
    description:"World-famous for glassmaking since 1291. Watch master glassblowers at work and browse showrooms. A short vaporetto ride from Venice proper.",
    notes:"Take vaporetto line 4.1 or 4.2 from Fondamente Nove.", source:"Must-see", verdict:"worth-it",honest_summary:"Watching a master glassblower work is genuinely mesmerizing. The showrooms range from tacky tourist souvenirs to stunning museum-quality art. Free glass-blowing demos are easy to find. The island itself is less charming than Burano - it is more industrial. Combine with Burano for a full day trip.",best_for:"Glass art fans and anyone doing the Murano-Burano day trip. The demos are free and fascinating.",visited:false },
  { id:"l15", name:"Burano Island", city:"Venice", category:"activity", lat:45.4853, lng:12.4167,
    description:"Instagram-famous for its brightly painted fisherman's houses. Known for lace-making tradition and seafood restaurants. The most colorful place in Venice.",
    notes:"45 min vaporetto from Venice. Combine with Murano for a day trip.", source:"Must-see", verdict:"essential",honest_summary:"The most photogenic spot in the Venice lagoon. Every house is painted a different bright color and it looks like a movie set. The lace-making tradition is real but fading. Good seafood restaurants here too. It is 45 minutes by vaporetto, so commit to a half-day. Combine with Murano on the way.",best_for:"Photographers and anyone who wants the most Instagram-worthy spot near Venice. Worth the boat ride.",visited:false },
  // ── LAKE COMO LANDMARKS ──
  { id:"l16", name:"Villa del Balbianello", city:"Lake Como", category:"landmark", lat:45.9650, lng:9.2050,
    description:"18th-century villa on a wooded promontory with spectacular lake views. Famous as a Star Wars and James Bond filming location. Gorgeous terraced gardens.",
    notes:"Book tour in advance. Water taxi from Lenno or 1km walk.", source:"Must-see", verdict:"essential",honest_summary:"Arguably the most beautiful villa on Lake Como. The setting on a wooded promontory is dramatic - you have seen it in Star Wars and Casino Royale. The terraced gardens are immaculate. Getting there requires either a water taxi from Lenno or a 1km walk. Book the villa tour in advance. This is the postcard image of Lake Como.",best_for:"The must-see villa on Como. Movie fans, garden lovers, and anyone who wants THE Lake Como photo. Book ahead.",visited:false },
  { id:"l17", name:"Villa Melzi Gardens", city:"Lake Como", category:"landmark", lat:45.9820, lng:9.2620,
    description:"Neoclassical villa with stunning lakeside gardens in Bellagio. Azaleas, rhododendrons, Japanese water gardens, and ancient trees. A peaceful escape from Bellagio's bustle.",
    notes:"Open March-October. €8 entry. No villa interior access.", source:"Must-see", verdict:"worth-it",honest_summary:"A peaceful escape from Bellagio's bustling center. The lakeside gardens are gorgeous - azaleas, Japanese water gardens, ancient trees. No villa interior access, just the grounds. Best in spring when everything is blooming, but still lovely in June. A quiet hour of beauty.",best_for:"A calm afternoon walk when Bellagio feels too crowded. Garden lovers and couples wanting a quiet lakeside stroll.",visited:false },
  { id:"l18", name:"Bellagio Waterfront", city:"Lake Como", category:"activity", lat:45.9860, lng:9.2595,
    description:"The 'Pearl of Lake Como' — stunning promenade where the three branches of the lake meet. Pastel-colored buildings, boutiques, and lakefront cafés. Pure honeymoon material.",
    notes:"Walk the Punta Spartivento promontory for incredible views.", source:"Must-see", verdict:"essential",honest_summary:"Where the three branches of Lake Como meet, and it is as stunning as advertised. The promenade with pastel buildings and lakefront cafes is pure honeymoon material. Walk out to Punta Spartivento for the best panoramic views. Can get crowded midday with day-trippers - mornings and evenings are magic.",best_for:"Everyone staying on Como. The waterfront promenade at golden hour is non-negotiable honeymoon time.",visited:false },
  { id:"l19", name:"Varenna Old Town", city:"Lake Como", category:"activity", lat:46.0105, lng:9.2835,
    description:"A colorful, quieter fishing village on Como's eastern shore. Walk the romantic Passeggiata degli Innamorati (Lovers' Walk) along the waterfront. Less touristy than Bellagio.",
    notes:"Easy to reach by train. Ferry to Bellagio takes 15 min.", source:"Must-see", verdict:"worth-it",honest_summary:"Quieter, more authentic, and less touristy than Bellagio. The Passeggiata degli Innamorati (Lovers Walk) along the waterfront is genuinely romantic. The colorful buildings cascading to the water are beautiful. Easy to reach by train, and the ferry to Bellagio is 15 minutes. A perfect half-day side trip.",best_for:"Couples who want a quieter alternative to Bellagio. The Lovers Walk is peak honeymoon. Take the ferry back.",visited:false },
  // ── FLORENCE RESTAURANTS (Goop guide) ──
  { id:"g3", name:"Trattoria 13 Gobbi", city:"Florence", category:"dining", lat:43.7725, lng:11.2487,
    description:"A Florentine institution near Santa Maria Novella. Rustic courtyard dining, beam ceilings, mismatched chairs, cured meats hanging everywhere. Famous for their rigatoni in ceramic tureen and bistecca alla fiorentina served medium-rare at room temperature — the proper Florentine way.",
    source:"Goop guide", duration_min:"90",cost:"€35–50/person",booking:"Book ahead — fills up nightly",best_time:"Dinner",transport:"Walk from S.M.N. station (5 min)",verdict:"essential",honest_summary:"Ask any Florentine where to take a visitor for their first dinner in the city and they will say 13 Gobbi. The rigatoni with cheese and tomato sauce is legendary - served in a ceramic tureen, rich and comforting. The bistecca is served medium-rare at room temperature, which is the correct Florentine way even if it surprises you. The courtyard seating feels like old Florence. Book ahead or get turned away.",best_for:"Your first dinner in Florence. The rigatoni and bistecca are the order. Book for the courtyard if weather allows.",visited:false },
  { id:"g4", name:"Il Santo Bevitore", city:"Florence", category:"dining", lat:43.7685, lng:11.2462,
    description:"One of Florence's most romantic restaurants in the Oltrarno district. Exposed stone walls, flickering candles, strong natural wine list with hundreds of bottles. Founded by three childhood friends passionate about ingredients and provenance. Wine bar Santino is right next door.",
    source:"Goop guide", duration_min:"90–120",cost:"€35–55/person",booking:"Book for dinner",best_time:"Dinner — summer streetside tables",transport:"Walk across Ponte Vecchio to Oltrarno",verdict:"essential",honest_summary:"The most romantic dinner in Florence. Candlelit stone walls, a natural wine list that goes deep, and food that is Tuscan tradition with just enough modern edge. The Oltrarno location feels like a different, quieter city from the tourist center. After dinner, continue next door at Santino (their wine bar) for another glass. This is the honeymoon dinner in Florence.",best_for:"Your romantic honeymoon dinner in Florence. Book a table for sunset, then wine bar next door after. Non-negotiable.",visited:false },
  { id:"g5", name:"Alla Vecchia Bettola", city:"Florence", category:"dining", lat:43.7630, lng:11.2430,
    description:"The essence of Florence since the late 1970s. Communal tables, hanging cured meats, carafes of house red, bottles of oil and vinegar on every table. Steak Florentine, fresh pasta, fruit and tiramisu for dessert. Strangers become friends at shared tables.",
    source:"Goop guide", duration_min:"90",cost:"€25–40/person",booking:"Recommended — limited seating",best_time:"Dinner",transport:"Walk from Oltrarno (15 min from Ponte Vecchio)",verdict:"worth-it",honest_summary:"The most authentic no-fuss Florentine dining experience. You will probably sit with strangers at communal tables, which sounds awkward but is actually the charm - the room fills with conversation and laughter. The steak Florentine is excellent, the house red flows freely, and the prices are fair. It is slightly farther from the center than other picks, which keeps it more local. Not romantic in a candlelit way - romantic in a life-is-good-and-we-are-in-Italy way.",best_for:"A lively, communal Tuscan dinner when you want authenticity over ambiance. The opposite of a polished tourist restaurant.",visited:false },
  // ── FLORENCE LANDMARKS ──
  { id:"f1", name:"Cathedral of Santa Maria del Fiore (Duomo)", city:"Florence", category:"landmark", lat:43.7731, lng:11.2560,
    description:"Florence's iconic cathedral crowned by Brunelleschi's dome — an engineering marvel of the Renaissance. Climb 463 steps to the top for panoramic city views. The baptistery doors are nicknamed the 'Gates of Paradise.'",
    notes:"Book dome climb tickets in advance! Free to enter cathedral, paid for dome/bell tower.", source:"Must-see", hours_open:"10:00",hours_close:"17:00",duration_min:"60–120",cost:"Free cathedral, €30 combo (dome+bell tower+museum)",booking:"Book dome climb online",best_time:"Early morning for dome climb",transport:"Walk from S.M.N. station (10 min)",accessibility:"Cathedral accessible; dome climb: 463 steps, no elevator",verdict:"essential",honest_summary:"Brunelleschi's dome is an engineering miracle that still holds up 600 years later. The cathedral itself is free and impressive but the dome climb is the real experience - 463 steps with no elevator, claustrophobic in places, but the panoramic view from the top is the best in Florence. The baptistery Gates of Paradise doors are also remarkable. Book the dome climb well ahead.",best_for:"Everyone. The dome climb is tough but unforgettable. If you skip the climb, the cathedral floor is still free and stunning.",visited:false },
  { id:"f2", name:"Uffizi Gallery", city:"Florence", category:"landmark", lat:43.7677, lng:11.2553,
    description:"One of the world's most important art museums. Home to Botticelli's Birth of Venus, works by Leonardo, Michelangelo, Raphael, and Caravaggio. Plan at least 3 hours.",
    notes:"MUST book timed entry tickets in advance — sells out in June.", source:"Must-see", hours_open:"8:15",hours_close:"18:30",duration_min:"180",cost:"€20–25",booking:"MUST book timed entry online",best_time:"Early morning or late afternoon",transport:"Walk from Ponte Vecchio (5 min)",accessibility:"Wheelchair accessible, elevator to upper floors",verdict:"essential",honest_summary:"One of the greatest art collections on Earth. But it is MASSIVE and exhausting if you try to see everything. Real talk: pick 10-15 works you care about and beeline for those. A guide makes the difference between \"nice paintings\" and \"life-changing experience.\"",best_for:"Art lovers and Renaissance fans. If art is not your thing, 90 minutes is plenty. If it is, block half a day.",visited:false },
  { id:"f3", name:"Ponte Vecchio", city:"Florence", category:"landmark", lat:43.7680, lng:11.2531,
    description:"Medieval stone bridge over the Arno, lined with jewelry shops since the 16th century. One of the most photographed spots in Italy. Beautiful at sunset from the riverside.",
    notes:"Walk across at golden hour for the best photos.", source:"Must-see", verdict:"worth-it",honest_summary:"Beautiful and iconic, but it is essentially a bridge with jewelry shops - you can see it in 10 minutes. The real value is the VIEW of Ponte Vecchio from the riverside or Piazzale Michelangelo. Do not eat at the restaurants on the bridge (tourist trap pricing). Walk across, take photos, move on.",best_for:"Everyone - 5-minute walk-through, not a destination. Best photographed from a distance at sunset.",visited:false },
  { id:"f4", name:"Galleria dell'Accademia", city:"Florence", category:"landmark", lat:43.7768, lng:11.2588,
    description:"Home to Michelangelo's original David — one of the most famous sculptures in the world. The marble masterpiece stands over 14 feet tall. Allow 1-2 hours.",
    notes:"Book tickets ahead. Consider a morning visit before the Duomo.", source:"Must-see", hours_open:"8:15",hours_close:"18:30",verdict:"essential",honest_summary:"You go for one thing: Michelangelo's David. And it delivers. The scale - over 14 feet of marble - is impossible to appreciate in photos. The rest of the museum is fine but secondary. Book timed entry or face a massive line. Budget 60-90 minutes unless you are really into the other collections.",best_for:"Everyone. The David is a must-see, full stop. Book morning tickets and pair with the Duomo nearby.",visited:false },
  { id:"f5", name:"Palazzo Pitti & Boboli Gardens", city:"Florence", category:"landmark", lat:43.7653, lng:11.2500,
    description:"Massive Renaissance palace that was home to the Medici family. Houses several museums plus the stunning Boboli Gardens — 11 acres of fountains, grottos, and sculptures.",
    notes:"Combined ticket covers palace museums + gardens. Good half-day activity.", source:"Must-see", hours_open:"8:15",hours_close:"18:30",verdict:"worth-it",honest_summary:"The Boboli Gardens are the star here - 11 acres of fountains, grottos, and sculptures that feel like a secret world. The palace museums are solid but can feel like museum fatigue after the Uffizi. Best strategy: buy the combo ticket, spend most of your time in the gardens, dip into the palace if energy allows. Good for a hot afternoon - lots of shade.",best_for:"Garden lovers and anyone needing a break from indoor museums. The gardens are the main event, not the palace.",visited:false },
  { id:"f6", name:"Piazzale Michelangelo", city:"Florence", category:"viewpoint", lat:43.7629, lng:11.2650,
    description:"Hilltop square with the most famous panoramic view of Florence — the Duomo, Palazzo Vecchio, Ponte Vecchio, and the Arno valley spread below. Magical at sunset.",
    notes:"Go for sunset! 20-minute uphill walk from the river or take bus 12/13.", source:"Must-see", verdict:"essential",honest_summary:"THE sunset spot in Florence. The panoramic view of the Duomo, Ponte Vecchio, and the Arno valley is the postcard shot of the city. Bring a bottle of wine and sit on the steps. 20-minute uphill walk but completely worth it. Also beautiful at sunrise.",best_for:"Everyone. Non-negotiable on a honeymoon. Go 45 minutes before sunset.",visited:false },
  { id:"f7", name:"San Lorenzo Leather Market", city:"Florence", category:"activity", lat:43.7748, lng:11.2537,
    description:"Bustling outdoor market surrounding the Basilica di San Lorenzo. Famous for handmade leather goods — bags, jackets, belts, wallets. Great for souvenir shopping and haggling.",
    notes:"Leather goods make great souvenirs. Bargain respectfully!", source:"Must-see", verdict:"nice",honest_summary:"A bustling outdoor market with leather goods everywhere - bags, jackets, belts, wallets. Quality varies wildly from tourist junk to genuine handmade pieces. The key is knowing what to look for and being willing to haggle respectfully. Good for souvenirs but not a must-see attraction. The Basilica di San Lorenzo nearby is worth a peek.",best_for:"Souvenir shoppers who want leather goods. Budget 30-45 minutes for browsing. Haggle but be respectful.",visited:false },
  { id:"f8", name:"Mercato Centrale", city:"Florence", category:"activity", lat:43.7761, lng:11.2535,
    description:"Florence's grand food hall — ground floor is a traditional market with fresh produce, meat, and cheese. Upper floor is a modern food court with artisan vendors. Perfect for a casual lunch.",
    notes:"Try lampredotto (tripe sandwich) — a classic Florentine street food.", source:"Must-see", verdict:"worth-it",honest_summary:"Two markets in one. The ground floor is a traditional Italian market - produce, meat, cheese, the real deal. The upper floor is a modern food court with artisan vendors. The lampredotto (tripe sandwich) is a classic Florentine street food worth trying even if it sounds weird. Great for a casual lunch without a restaurant commitment.",best_for:"Foodies who want to try lampredotto and browse a real Italian market. Perfect casual lunch spot.",visited:false },
  // ── TUSCANY ──
  { id:"t1", name:"Chianti Wine Region", city:"Tuscany", category:"activity", lat:43.5500, lng:11.2500,
    description:"Rolling hills covered in vineyards between Florence and Siena. The heart of Chianti Classico wine production. Dotted with medieval villages, olive groves, and cypress-lined roads. Pure Tuscan honeymoon magic.",
    notes:"1 night agriturismo planned here June 21-22. Need driver/car from Florence.", source:"Trip planning", verdict:"essential",honest_summary:"The Tuscan countryside between Florence and Siena is everything you imagine - rolling hills, vineyards, cypress-lined roads, medieval villages. Staying overnight at an agriturismo is the right call. You need a car or driver to explore properly. Wine tastings at small family estates are the highlight. This is where the trip shifts from sightseeing to experiencing.",best_for:"The honeymoon highlight. One night in an agriturismo with wine, views, and nowhere to be. Do not rush this.",visited:false },
  { id:"t2", name:"San Gimignano", city:"Tuscany", category:"landmark", lat:43.4677, lng:11.0437,
    description:"Medieval hilltop town famous for its 14 surviving tower houses — the 'Manhattan of the Middle Ages.' UNESCO World Heritage Site. Great local Vernaccia white wine and gelato.",
    notes:"Possible day trip or near the Tuscany overnight stay.", source:"Must-see", verdict:"worth-it",honest_summary:"The 14 medieval towers make it look like a tiny Manhattan, and the hilltop setting is dramatic. UNESCO World Heritage for good reason. The local Vernaccia white wine is excellent. Gelateria Dondoli has award-winning gelato. Can get very crowded midday with tour buses - go early or late. Works as a half-day trip from the Chianti agriturismo.",best_for:"A half-day side trip from Chianti or Siena. The towers, wine, and gelato make it worth the detour.",visited:false },
  // ── AMALFI / DAY TRIP ──
  { id:"a1", name:"Amalfi Coast / Positano (Day Trip)", city:"Rome", category:"activity", lat:40.6280, lng:14.4850,
    description:"Dramatic cliffside villages, turquoise water, lemon groves. Positano is the most famous and photogenic town. Can be done as a day trip from Rome via guided tour (~€100-150/person) or train to Salerno + ferry.",
    notes:"DAY TRIP from Rome during June 13-18 stay. Ask travel agent about guided tour options. Keep this on a separate day from Pompeii — don't rush it. Arrive mid-morning, long lunch on a terrace, soak it in.", source:"Trip planning", verdict:"essential",honest_summary:"The cliffside villages and turquoise water are genuinely jaw-dropping. Positano is the most photogenic but also the most crowded and expensive. A day trip from Rome is doable but long - guided tours run about 100-150 euros per person. The key is not rushing: arrive mid-morning, have a long lunch on a terrace overlooking the sea, and soak it in. Do NOT combine with Pompeii in the same day.",best_for:"The big wow day trip. Keep a separate day from Pompeii. Long lunch on a cliff terrace is the honeymoon moment.",visited:false },
  { id:"a2", name:"Pompeii (Day Trip)", city:"Rome", category:"landmark", lat:40.7484, lng:14.4848,
    description:"Ancient Roman city frozen in time by the eruption of Mount Vesuvius in 79 AD. Remarkably preserved streets, houses, frescoes, and public buildings. One of the most important archaeological sites in the world. ~1 hour train from Rome to Naples, then 30 min to Pompeii.",
    notes:"DAY TRIP from Rome during June 13-18 stay. Separate day from Amalfi. Book skip-the-line entry. Wear comfortable shoes and bring water — it's a huge open-air site with little shade in June.", source:"Trip planning", verdict:"essential",honest_summary:"An entire Roman city frozen in volcanic ash - streets, houses, frescoes, and public buildings preserved for 2,000 years. It is HUGE and mostly open-air with little shade, so June heat is real. Bring water, wear comfortable shoes, and book skip-the-line entry. A guide brings it to life - without one it can feel like walking through endless ruins. Budget 3-4 hours minimum.",best_for:"History buffs will spend all day here. Everyone else should budget 3 hours with a guide. Stop in Naples for pizza on the way.",visited:false },
  { id:"a3", name:"L'Antica Pizzeria da Michele (Naples)", city:"Rome", category:"dining", lat:40.8496, lng:14.2626,
    description:"The most famous pizzeria in the world, open since 1870. Only serves two pizzas: Margherita and Marinara. Featured in Eat Pray Love. Naples is the birthplace of pizza and this is its temple. Stop here on the way to or from Pompeii.",
    notes:"NAPLES STOP on Pompeii day trip. Train passes through Naples — grab pizza on the way. Cash only. Expect a line but it moves fast.", source:"Trip planning", verdict:"essential",honest_summary:"The most famous pizzeria on Earth, open since 1870, and it only serves two pizzas: Margherita and Marinara. That is confidence. The pizza is perfect - simple, blistered, and cheap. Cash only. The line looks intimidating but moves fast. Naples is the birthplace of pizza and this is its temple. Stop here on the Pompeii day trip - the train passes right through.",best_for:"Everyone on the Pompeii day trip. Stop in Naples, eat the best Margherita of your life, get back on the train.",visited:false },
  // ── VERONA STOPOVER ──
  { id:"ver1", name:"Verona Arena", city:"Venice", category:"landmark", lat:45.4391, lng:10.9946,
    description:"Remarkably well-preserved Roman amphitheater from the 1st century AD — older than the Colosseum. Seats 15,000 and still hosts opera performances in summer. Third largest arena in Italy.",
    notes:"VERONA STOPOVER June 24 on the way from Como to Venice. Luggage storage at Verona Porta Nuova station (~€5). 3-4 hours in the city is enough.", source:"Trip planning", verdict:"worth-it",honest_summary:"Older than the Colosseum and remarkably well-preserved. It still hosts opera performances in summer, which is incredible. The arena itself takes 30-45 minutes to explore. Verona is a natural stopover between Como and Venice, and 3-4 hours in the city is plenty. Store luggage at the train station for about 5 euros.",best_for:"A worthwhile stopover on the Como-to-Venice travel day. See the arena, grab lunch, continue to Venice.",visited:false },
  { id:"ver2", name:"Juliet's Balcony (Casa di Giulietta)", city:"Venice", category:"landmark", lat:45.4421, lng:10.9988,
    description:"The legendary balcony from Shakespeare's Romeo and Juliet. Whether or not the story is real, the 14th-century courtyard and balcony are a must-see romantic stop — perfect for the honeymoon.",
    notes:"VERONA STOPOVER. Free to see the courtyard and balcony from below. Small fee to go inside and stand on the balcony.", source:"Trip planning", verdict:"nice",honest_summary:"Is it the real balcony from Romeo and Juliet? No - Shakespeare never visited Verona and the story is fictional. Is it still a fun, romantic stop? Absolutely. The 14th-century courtyard is free to see from below, small fee to stand on the balcony. It is cheesy in the best way. On a honeymoon, you lean into it.",best_for:"Honeymooners who want a cheesy romantic photo. Takes 15 minutes. Free from the courtyard below.",visited:false },
  { id:"ver3", name:"Piazza delle Erbe", city:"Venice", category:"activity", lat:45.4430, lng:10.9975,
    description:"Verona's most picturesque square, built on the site of the ancient Roman forum. Surrounded by medieval and Renaissance buildings, frescoed facades, and the Torre dei Lamberti. Great spot for a lunch stop.",
    notes:"VERONA STOPOVER. Good lunch spot — grab a table and people-watch.", source:"Trip planning", verdict:"worth-it",honest_summary:"Verona's most beautiful square, built on the ancient Roman forum. Surrounded by frescoed medieval buildings and the Torre dei Lamberti. Great spot for a lunch stop during the Verona layover. Grab a table, order a glass of Amarone, and people-watch. This is the natural center of a Verona visit.",best_for:"Lunch stop during the Verona layover. The square is beautiful and centrally located between the Arena and Juliet's Balcony.",visited:false },
  // ── TRANSIT STATIONS ──
  { id:"tr1", name:"Roma Termini Station", city:"Rome", category:"transit", lat:41.9013, lng:12.5017,
    description:"Rome's main train station and central transport hub. Departure point for all intercity trains. Metro Lines A & B intersect here. Shops, cafes, and luggage storage inside.",
    notes:"Our train to Florence departs from here June 18. Luggage storage available.", source:"Infrastructure", visited:false },
  { id:"tr2", name:"Firenze S.M.N. Station", city:"Florence", category:"transit", lat:43.7764, lng:11.2479,
    description:"Florence's central station (Santa Maria Novella). Arrival point from Rome, departure for the north. Right in the historic center — walk to the Duomo in 10 minutes.",
    notes:"Arrive from Rome June 18. Depart for Tuscany June 21.", source:"Infrastructure", visited:false },
  { id:"tr3", name:"Venezia Santa Lucia Station", city:"Venice", category:"transit", lat:45.4413, lng:12.3210,
    description:"Venice's main train station, right on the Grand Canal. Exit the station and you're immediately in Venice. Vaporetto (water bus) stops right outside. Luggage storage available.",
    notes:"Arrive from Verona June 24. Depart for home June 27.", source:"Infrastructure", visited:false },
  { id:"tr4", name:"Como San Giovanni Station", city:"Lake Como", category:"transit", lat:45.8083, lng:9.0849,
    description:"Lake Como's main station. Trains to/from Milan (1 hr) and Venice (3.5 hrs). Buses and ferries to Bellagio and Varenna depart nearby.",
    notes:"Arrive from Tuscany/Florence area June 22.", source:"Infrastructure", visited:false },
  // ── PHARMACIES ──
  { id:"ph1", name:"Farmacia near DoubleTree Monti", city:"Rome", category:"pharmacy", lat:41.8960, lng:12.4967,
    description:"Pharmacy in the Monti district near the hotel. Good to know the location in advance for any medication needs.",
    notes:"Near our hotel. Look up exact address closer to trip.", source:"Infrastructure", visited:false },
  // ── VIEWPOINTS ──
  { id:"vp1", name:"Punta Spartivento", city:"Lake Como", category:"viewpoint", lat:45.9895, lng:9.2575,
    description:"The tip of the Bellagio promontory where the three branches of Lake Como meet. Panoramic views in every direction. Possibly the most romantic viewpoint on the lake.",
    notes:"Walk here from Bellagio center — perfect sunset spot.", source:"Must-see", verdict:"essential",honest_summary:"The tip of the Bellagio promontory where all three branches of Lake Como spread out before you. Panoramic views in every direction. It is a short walk from Bellagio center and completely free. Possibly the most romantic viewpoint on the entire lake. Go at sunset with a bottle of wine.",best_for:"Your sunset spot on Lake Como. Walk here from Bellagio, bring wine, watch the light change over the lake. Non-negotiable.",visited:false },
  // ── FLORENCE RESTAURANTS (Oltrarno Splendid hotel recs) ──
  { id:"os1", name:"Trattoria I'Raddi", city:"Florence", category:"dining", lat:43.7667, lng:11.2448,
    description:"Authentic Tuscan trattoria in the Oltrarno with an informal, easygoing atmosphere. Recommended by the Oltrarno Splendid hotel — walking distance from your room.",
    source:"Oltrarno Splendid rec", transport:"Via D'Ardiglione, 47 — short walk from hotel", visited:false },
  { id:"os2", name:"La Casalinga", city:"Florence", category:"dining", lat:43.7666, lng:11.2485,
    description:"A Florence institution since 1963. The name means 'the housewife' — hearty, no-nonsense Tuscan home cooking at honest prices. Always packed with locals and in-the-know visitors. The ribollita and pappa al pomodoro are classics.",
    source:"Oltrarno Splendid rec", transport:"Via dei Michelozzi, 9/r — short walk from hotel", visited:false },
  { id:"os3", name:"I'Brindellone", city:"Florence", category:"dining", lat:43.7686, lng:11.2427,
    description:"Neighborhood trattoria on a quiet Oltrarno piazza. Good authentic Tuscan food in an informal setting. The kind of place where regulars have their usual table.",
    source:"Oltrarno Splendid rec", transport:"Piazza Piattellina, 10/r — short walk from hotel", visited:false },
  { id:"os4", name:"Antico Ristoro del Cambi", city:"Florence", category:"dining", lat:43.7711, lng:11.2423,
    description:"Classic Florentine trattoria known for its bistecca alla fiorentina and traditional Tuscan dishes. Rustic interior with a loyal local following. One of the more established spots in the Oltrarno dining scene.",
    source:"Oltrarno Splendid rec", transport:"Via S.Onofrio, 1/r — short walk from hotel", visited:false },
  { id:"os5", name:"Trattoria Sant'Agostino", city:"Florence", category:"dining", lat:43.7674, lng:11.2459,
    description:"Cozy Oltrarno trattoria on a quiet street. Authentic Tuscan cooking with an easygoing vibe — the kind of neighborhood spot the hotel trusts enough to recommend.",
    source:"Oltrarno Splendid rec", transport:"Via Sant'Agostino, 23 — short walk from hotel", visited:false },
  { id:"os6", name:"Trattoria 4 Leoni", city:"Florence", category:"dining", lat:43.7671, lng:11.2504,
    description:"Popular Oltrarno trattoria on the charming Piazza della Passera. Known for pear-and-pecorino ravioli and classic Florentine dishes. Outdoor seating on the piazza is the move in summer.",
    source:"Oltrarno Splendid rec", transport:"Via dei Vellutini, 1/r — short walk from hotel", visited:false },
  { id:"os7", name:"Il Guscio", city:"Florence", category:"dining", lat:43.7691, lng:11.2404,
    description:"Small, intimate Oltrarno restaurant with a creative take on Tuscan classics. Slightly more refined than the neighborhood trattorias but still casual and welcoming.",
    source:"Oltrarno Splendid rec", transport:"Via dell'Orto, 49 — short walk from hotel", visited:false },
];

// ═══════════════════════════════════════
// AUTO-TAG ENGINE
// ═══════════════════════════════════════
function autoTag(place) {
  const tags = [];
  const desc = (place.description || '').toLowerCase();
  const cat = place.category;

  if (cat === 'landmark' || desc.includes('ancient') || desc.includes('century') || desc.includes('historic') || desc.includes('medieval')) tags.push('historic');
  if (cat === 'dining' || desc.includes('food') || desc.includes('restaurant') || desc.includes('cuisine') || desc.includes('gelato') || desc.includes('pizza') || desc.includes('wine')) tags.push('foodie');
  if (desc.includes('romantic') || desc.includes('honeymoon') || desc.includes('love') || desc.includes('intimate') || cat === 'viewpoint') tags.push('romantic');
  if (desc.includes('free') || desc.includes('cheap') || desc.includes('under €') || desc.includes('budget') || desc.includes('no-frills')) tags.push('budget');
  if (cat === 'viewpoint' || desc.includes('garden') || desc.includes('park') || desc.includes('walk') || desc.includes('outdoor') || desc.includes('lake') || desc.includes('island')) tags.push('outdoor');
  if (desc.includes('evening') || desc.includes('night') || desc.includes('sunset') || desc.includes('cocktail') || desc.includes('bar') || desc.includes('aperitivo')) tags.push('evening');
  if (desc.includes('quick') || desc.includes('grab') || desc.includes('bakery') || desc.includes('slice') || desc.includes('gelato') || desc.includes('café') || desc.includes('caffè') || desc.includes('coffee')) tags.push('quick-bite');

  return [...new Set(tags)];
}

// Distance helpers
function distanceKm(lat1, lng1, lat2, lng2) {
  const R = 6371;
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLng = (lng2 - lng1) * Math.PI / 180;
  const a = Math.sin(dLat / 2) ** 2 + Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLng / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

function walkMinutes(km) { return Math.round(km / 0.07); }

function getNearbyPairings(place, maxKm) {
  maxKm = maxKm || 0.6;
  const allPlaces = Storage.getPlaces();
  return allPlaces
    .filter(function(p) { return p.id !== place.id && p.category !== 'transit' && p.category !== 'pharmacy' && p.category !== 'restroom'; })
    .map(function(p) { return Object.assign({}, p, { dist: distanceKm(place.lat, place.lng, p.lat, p.lng) }); })
    .filter(function(p) { return p.dist < maxKm; })
    .sort(function(a, b) { return a.dist - b.dist; })
    .slice(0, 4);
}
